### PR TITLE
hidden contributions

### PR DESCRIPTION
**Pull request by kylemcdonald**
i made a small change to almost all the poems, and saved a hidden and encrypted copy of that modified poem into its image.

### CODE REVIEW

**Comment by tchoi8** [comment]
still trying to think of clever thing to do before merging this pull. Can you share more clues about the encryption?

**Comment by kylemcdonald** [comment]
here is a (big) hint: i used this tool https://code.google.com/p/f5-steganography/

and the password is the same thing that i used to modify all the poems.

**Comment by tchoi8** [comment]
gonna merge this finally.

**Comment by kylemcdonald** [comment]
wooo :)

**Pull request merged**
