### PR TITLE
Create fork.md

### PR DESCRIPTION
**Pull request by raphaelbastide**

### CODE REVIEW

**Comment by tchoi8** [comment]
haha this is great. thanks!

**Comment by raphaelbastide** [comment]
It is supposed to be in poems/, sorry.

**Comment by tchoi8** [comment]
Hi Raphael. I tried to moving it to poems and accidentally deleted the file that I pulled. I'll try to go back in time and fix it!

**Comment by raphaelbastide** [comment]
No problem, good luck with time-travel.

**Comment by tchoi8** [comment]
ok cool time travel is fun.

i think ill leave it on the head directory for now.
the repo is meant to be a playground, we don't really need rules.
lets see what other people do!

**Comment by raphaelbastide** [comment]
This is a cool project.
I think we have interests in common. I can send you a mail with some links about versioning in art. Also, I am really curious about http://sfpc.io/ and I will read all of it soon!

**Pull request merged**
